#!/bin/sh

#= auto build example

## hyphop ##

set -e

export LINUX_VER=linux-5.3-rc6

./kernel_prepare
./patch_ ../patches/0001-vim3.patch
./patch_ ../patches/0002-fix_usb3_otg_port_to_device_mode.patch
./patch_ ../patches/gitignore-local-fix.patch
./patch_ ../patches/0185-arm64-dts-VIM1-add-thermal-zones.patch
./patch_ ../patches/0333-exfat.patch
#./patch_ ../patches/wifi/board-VIM1-0069-fix.patch
./patch_ ../patches/wifi/board-VIM1-fixup-btbcm.patch
./patch_ ../patches/linux-5.4-rc5/0030-fix-broken-ethernet-interface-up-down.patch
./patch_ ../patches/wifi2/*.patch

./prepare_

./make_kernel_mainline_vimsX -n
./kernel_config ../files/configs/mmc_y
./kernel_config ../files/configs/eth2_y

NOPOST=1 ./make_kernel_mainline_vimsX dtbs
#exit 0
NOPOST=1 ./make_kernel_mainline_vimsX

TAR=1 ./make_kernel_mainline_vimsX_modules
