#!/bin/sh

#= auto build example

## hyphop ##

set -e

./kernel_prepare
./patch_ ../patches/linux-5.4.-rc5/*.patch

#./prepare_

./make_kernel_mainline_vimsX -n
./kernel_config ../files/configs/mmc_m
./kernel_config ../files/configs/eth2_y

./make_kernel_mainline_vimsX
TAR=1 ./make_kernel_mainline_vimsX_modules
