#!/bin/sh

## hyphop ##

#= download kernel source

#set -e 

D=$(dirname $0)
N=$(basename $0)
DR=$(realpath $D)

. "$DR/config.conf"

TO="$D/$TO2"

uid=$(id -u)
gid=$(id -g)

CMD(){
    echo "">&2
    $@
}

DL(){
    
    echo "[i] download $DOWNLOAD_BASE/$1 $2">&2
    curl -jkL "$DOWNLOAD_BASE/$1" -o "$2" -C- -#
}

for LINK in $LINUX_SRC_SFS ; do

FILE=$(basename $LINK)

DL "$LINK" "$TO$FILE"

echo "[i] $FILE">&2

T="$(realpath "$KERNEL_PATH2/${FILE%.*}")"

grep "$T" /proc/mounts || {
    CMD $DR/mount_overlay_squash "$TO$FILE" "$T"
}

done

for LINK in $GCC_SRC_SFS; do

FILE=$(basename $LINK)

DL "$LINK" "$TO$FILE"

T="$(realpath "$GCC_PATH")"

grep "$T" /proc/mounts || {
    CMD sudo mount "$TO$FILE" "$T"
}
done



