#!/bin/sh

## hyphop ##

#= make kernel wrapper

#/ USAGE $0 [ARGS]
#/ args:
#/ menuconfig
#/ dtbs
#/ -jN
#/ savedefconfig
#/ Image
#/ help
#/ ...

set -e 

D=$(dirname $0)
N=$(basename $0)
DR=$(realpath $D)

export PATH=$(realpath $D/../../fenix/build/toolchains/gcc-linaro-aarch64-linux-gnu/bin):$PATH
export ARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-

for DIR in $D/../../fenix/build/linux-mainline-*; do
    [ -d "$DIR" ] && break
done

CMD(){
    echo "[#] $@">&2
    "$@"
}

# cross gcc test
CMD ${CROSS_COMPILE}gcc --version  || {
    echo "[e] cross gcc failed">&2
    exit 1
}

#./,make_kernel_vims ../../../../kvims_light_defconfig

CMD make -C "$DIR" "$@"

# post

T=/tmp/$N

[ -d /tmp/modules ] || \
    mkdir /tmp/modules

ln -sf /tmp/modules $T

#cp $DIR/defconfig $T/defconfig
[ -f $T/config.gz ] && \
CMD mv $T/config.gz $T/config.gz.old
CMD gzip -c $DIR/.config > $T/config.gz
CMD cp $DIR/arch/arm64/boot/dts/amlogic/*vim*.dtb $T
#cp $DIR/arch/arm64/boot/dts/amlogic/*vim2*.dtb $T/linux.dtb
#dtc $T/linux.dtb > $T/linux.dts 2>/dev/null
CMD cp $DIR/arch/arm64/boot/Image* $T
