#!/bin/sh

## hyphop ##

./mount_overlay_squash /tmp/linux-5.? -c
./mount_overlay_squash /tmp/linux-5.? -df

./mount_overlay_squash /tmp/linux-5.?-rc? -c
./mount_overlay_squash /tmp/linux-5.?-rc? -df

./mount_overlay_squash /tmp/linux-5.?.? -c
./mount_overlay_squash /tmp/linux-5.?.? -df

./mount_overlay_squash /tmp/linux-5.?.?? -c
./mount_overlay_squash /tmp/linux-5.?.?? -df
